name: chat_app
description: Chat app Flutter + Supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.10.3
  provider: ^6.1.5+1
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  fluttertoast: ^8.2.1
  http: ^0.13.6
  path_provider: ^2.0.13
  intl: ^0.19.0 
  google_fonts: 4.0.4
  cached_network_image: ^3.3.1
  firebase_storage: ^13.0.4

flutter:
  assets:
    - assets/icons/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
